App\Entity\Component:
    type: entity
    table: null
    repositoryClass: App\Repository\ComponentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
        type:
            type: string
    manyToOne:
        ad:
            targetEntity: Ad
            inversedBy: components
            cascade: ["persist", "merge"]
    lifecycleCallbacks: {  }
